version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ocev-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: OCEV
      POSTGRES_PASSWORD: OCEVPass
      POSTGRES_DB: OCEVDatabase

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: